# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Robin K Wilson
email: robin.kath.wilson@gmail.com
description: # >- this means to ignore newlines until "baseurl:"
  Robin K Wilson's personal website. The site serves as a platform to showcase her projects, contributions, and overall learning. Resume and CVs are available!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  robin-k-wilson

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
# minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed

include: ["_pages"]

author:
  name: "Robin K Wilson"
  avatar: "/assets/img/robinHeadshot1_thumbnail.jpg"
  # bio: "My awesomeness can not be contained by a small biography."
  location: Oakland, CA
  email: "hello"
  linkedin: robinkwilson25/
  github: robin-k-wilson
  uri: http://robinkwilson.com

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "assets/img"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
