title: Robin K. Wilson
email: robin.kath.wilson@gmail.com
description: # >- this means to ignore newlines until "baseurl:"
  Robin K. Wilson's personal website. The site serves as a platform to showcase her projects, contributions, and overall learning. Resume and CVs are available!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  robin-k-wilson

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.13.0"
# minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

include: ["_pages"]

author:
  name: "Robin K. Wilson"
  avatar: "/assets/img/robinHeadshot1_thumbnail.jpg"
  location: San Francisco, CA
  linkedin: robinkwilson/
  github: robin-k-wilson
  # uri:

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "assets/img"
    values:
      image: true

head_scripts:
  - /assets/js/form.js

footer_scripts:
  - /assets/js/main.min.js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
